# Nabu's sensors are owned by SLPI and exposed through SSC over QRTR.
[Unit]
Wants=hexagonrpcd.service
After=hexagonrpcd.service

[Service]
Restart=always
RestartSec=1s
RestrictAddressFamilies=AF_UNIX AF_LOCAL AF_NETLINK AF_QIPCRTR
